### ISSUE TITLE
Issue when signing up/logging in

### ISSUE THREAD

**Issue by kkrauth** [kmacancela/currency-conversion#1]
Hi!

Running into the same issue when signing up or logging in. Here is the trace for login flow:

```
Started POST "/login" for ::1 at 2020-02-27 15:40:00 -0500
Processing by LoginController#create as JSON
  Parameters: {"email"=>"test@mastercard.com", "password"=>"[FILTERED]", "login"=>{"email"=>"test@mastercard.com", "password"=>"[FILTERED]"}}
  Account Load (0.5ms)  SELECT "accounts".* FROM "accounts" WHERE (lower(email) = 'test@mastercard.com') LIMIT $1  [["LIMIT", 1]]
  ↳ app/controllers/login_controller.rb:3:in `create'
Completed 500 Internal Server Error in 233ms (ActiveRecord: 0.5ms | Allocations: 850)
  
TypeError (no implicit conversion of nil into String):
  
app/controllers/application_controller.rb:3:in `create_token'
app/controllers/login_controller.rb:5:in `create'
```

The user is successfully inserted into the database during signup process in spite of the error shown in the signup form.

Let me know if you have any thoughts about what might be causing it! Using Ruby 2.6.1 with Rails 6.0.2.1.

**Comment by kmacancela** [comment]
Hi Kosta, I believe the issue here is that you do not import the dotenv file when you clone this repo. I can send you an email with the variable that is required for hashing passwords and hence fixing this error. Should I reply to this thread or to a different email? Feel free to email be directly so I can forward you this file.
